# Download TensorFlow Docker Package
# https://www.tensorflow.org/install/docker

FROM nvcr.io/nvidia/tensorflow:22.08-tf2-py3 AS build
WORKDIR /zooper2/jacob.khalili
SHELL ["/bin/bash", "-c"] 


