# Download TensorFlow Docker Package
# https://www.tensorflow.org/install/docker

FROM nvcr.io/nvidia/tensorflow:22.08-tf2-py3 as build
ADD /zooper2/jacob.khalili /zooper2/jacob.khalili
WORKDIR /zooper2/jacob.khalili
SHELL ["/bin/bash", "-c"] 


